app = "ekinox-socket-server"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile.socket"

[http_service]
  internal_port = 3002
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "2gb"
  cpu_kind = "performance"
  cpus = 1

[env]
  NODE_ENV = "production"
  PORT = "3002"
